### ISSUE TITLE
vistorlog can't work?

### ISSUE THREAD

**Issue by xiaoyaoxuanku** [MyShiLingStar/ACNHPokerCore#10]
![屏幕截图 2022-05-06 095042](https://user-images.githubusercontent.com/88808554/167054593-1416e6ff-9b3c-411f-a9d7-bb8404938898.png)
Is there someting wrong with it? how to use?

**Comment by MyShiLingStar** [comment]
Nothing wrong.

1. Use "Create Map Template" to make a map savefile.
2. Use "Cast Regen" or "Cast Moogle Regenja" to start the regen.
- "Cast Regen" does not ignore empty space.
- "Cast Moogle Regenja" ignores empty space.
3. (Optional) Enable the "Dodo Helper" if needed.

**Comment by xiaoyaoxuanku** [comment]
thank you very much
