### ISSUE TITLE
RoadRoller

### ISSUE THREAD

**Issue by adolncom** [MyShiLingStar/ACNHPokerCore#13]
Thank you for all the updates.
The RoadRoller is a great feature, but I would like to specify RoadStone's 8A for use.
![image](https://user-images.githubusercontent.com/67450852/173383393-bbcd9677-3e59-4016-abb0-0028554c6676.png)

**Comment by MyShiLingStar** [comment]
The current design of Road Roller is to let the user paint without knowing all the specific models.
It selects the "correct" one automatically as the user paints.
I called it the **Smart mode** for the time being.

If no major bugs are found in the **Smart mode**, I will try to add a **Manual mode** in the next update.

**Comment by adolncom** [comment]
Thank you for a really great feature.
I am really looking forward to the update.

**Comment by MyShiLingStar** [comment]
[1819349](https://github.com/MyShiLingStar/ACNHPokerCore/commit/1819349ee71703e4b00dfe4e9f1b30962dacf1ad)
