### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by chimel23** [MyShiLingStar/ACNHPokerCore#14]
The app doesn't work. I installed the runtime, tried both 5.0 and 6.0 and am still told to install the runtime. So what's the problem??

**Comment by MyShiLingStar** [comment]
Please double-check that you are installing the **Desktop Runtime**.


And thanks to Microsoft. The runtime install could fail for no reason.
You can try running the installer again.
Then select repair.
Restart your computer after the repair.
Then try to run the app again.

![Repair](https://user-images.githubusercontent.com/816502/175753607-e097e91e-d465-4283-8b67-17e2378bde6b.png)

**Comment by chimel23** [comment]
Ok. I’m also uninstalling the older frameworks and then I’ll try a clean install again

**Comment by chimel23** [comment]
It has to be something else. None of that worked

**Comment by moddedx** [comment]
> It has to be something else. None of that worked

have you rebooted after installing it?

**Comment by chimel23** [comment]
Yeah

**Comment by MyShiLingStar** [comment]
Once again please double-check you are installing the correct file. 
The file name should be `windowsdesktop-runtime-5.0.17-win-x64.exe`.

And I believe you actually need to do a "Repair" if it does not work.

1. Run `windowsdesktop-runtime-5.0.17-win-x64.exe` and install it the first time.
2. Run `windowsdesktop-runtime-5.0.17-win-x64.exe` again and do a "Repair".
3. Reboot the computer after the repair.

**Comment by XenonMazi** [comment]
Hello. So I've tried the above steps and it won' t work. It keeps telling me the .NET isn't installed. It Shows this. So I did try uninstalling and then reinstalling, restarting my computer between each step. I tried this about three times after reading this post. Are there computer requirements to run ACNHPokerCore?
![Capture](https://user-images.githubusercontent.com/108363978/176257942-6cf13fed-f21e-4b61-acd8-1df250925c86.PNG)

**Comment by MyShiLingStar** [comment]
The only computer requirement is running an x64 version of Windows 7 or above.


1. Make sure you are installing the `Desktop Runtime`. You can download it from [here](https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime).

![image](https://user-images.githubusercontent.com/816502/177071466-501306c1-6068-4cc4-a6c6-260a3c713aa9.png)

2. The file name is `windowsdesktop-runtime-5.0.17-win-x64.exe`.

![image](https://user-images.githubusercontent.com/816502/177071790-f7bea13a-95e1-4fba-9632-0e656729d59e.png)
![image](https://user-images.githubusercontent.com/816502/177071856-c25ff6df-d8bb-477a-9926-b3363b14c65a.png)

3. If it does not work for your first install. Run it again and select `Repair`.

![image](https://user-images.githubusercontent.com/816502/177071890-ba3b6f32-fa25-43e4-9f7a-a1b2227ef61f.png)
![image](https://user-images.githubusercontent.com/816502/177072092-8b037a81-5352-4824-992a-6d3cf9c92c4c.png)

4. Please restart your PC after the repair
