### ISSUE TITLE
No response in the game about the content of chat function input

### ISSUE THREAD

**Issue by Ic-any** [MyShiLingStar/ACNHPokerCore#16]
When I input text in the chat function, but the chat box in the game doesn't respond
![image](https://user-images.githubusercontent.com/92638461/175969367-1abe34c8-f6f9-485f-a57a-8d15492a90d9.png)

**Comment by Ic-any** [comment]
Press the R key first, then input the content you need to display in chat, and then input any text in the game material border to display the text entered in chat, such as

**Comment by Ic-any** [comment]
However, this has become troublesome again. However, I recently discovered this problem. If this problem is not triggered, you can enter good content and press enter to display the content I have entered in the game

**Comment by MyShiLingStar** [comment]
https://user-images.githubusercontent.com/816502/176070652-194a70a2-1beb-472e-ac80-94089b34587c.mp4

You can't have any controller connected.

The yellow/green pro controller in the video is the virtual controller.
You need to give the control to the virtual controller for the chat to work.

**Comment by Ic-any** [comment]
It seems that the virtual handle can't be connected to my machine

**Comment by Ic-any** [comment]
There is no connection in the handle interface

**Comment by Ic-any** [comment]
In fact, it is very simple to solve this problem. You can click detach on the Dutch sailors in the Dodo help interface to solve this problem. Thank you for your video, which provides me with ideas to solve this problem.

**Comment by Ic-any** [comment]
![Uploading image.png…]()

**Comment by MyShiLingStar** [comment]
![image](https://user-images.githubusercontent.com/816502/176084457-8ff8a407-1d5e-4f6a-a5e2-471ee92022c2.png)

I added an extra button so that you can easily connect the controller without going to the dodo helper.

**Comment by Ic-any** [comment]
ok
