### ISSUE TITLE
not a issue but a idea to auto-fill pocket.. add a switch   

### ISSUE THREAD

**Issue by ELY3M** [MyShiLingStar/ACNHPokerCore#20]
if you have no time...  I will add it in and do pull request.    
I would like to have my pockets auto fill sometimes.

**Comment by ELY3M** [comment]
I been working on it.  I got it working.   it flicks abit when it do autorefill your inventory.  
its worst if you have sound on.

**Comment by ELY3M** [comment]
I just did pull request :)

**Comment by MyShiLingStar** [comment]
b8f9c8e5d092e27a3d9f79358dd14f6b54389644
