### ISSUE TITLE
ACNHpoker cannot connect successfully when using accelerator to change automatic IP address

### ISSUE THREAD

**Issue by kutuo** [MyShiLingStar/ACNHPokerCore#22]
ACNHpoker cannot connect successfully when using accelerator to change automatic IP address
<img width="665" alt="截屏2022-07-10 06 14 21" src="https://user-images.githubusercontent.com/93738387/178124267-19ca721a-db21-48f7-8ab9-f63eb7944323.png">
<img width="940" alt="截屏2022-07-10 06 14 33" src="https://user-images.githubusercontent.com/93738387/178124279-dc90b90b-6d85-401b-96cf-9e83d22d5590.png">

**Comment by MyShiLingStar** [comment]
I have never used an "accelerator" before so I am not sure about its setting.  

All I know is both your PC and Switch need to be on the same network. (Like both should have IP on 172.24.124.XXX)  
And you need port (端口) 6000 open on the Switch's IP address.   

You can test the connection by doing a [ping] and [telnet] test.
![ping](https://user-images.githubusercontent.com/816502/178669556-90e43912-4452-4a68-acac-2ff0a67ed23f.png)

**Comment by kutuo** [comment]
Thank you, when the accelerator is not used, it can be connected normally, as shown in the figure. I can't connect as soon as I use the accelerator, but without using the accelerator, my NAT type is only C, and I can't connect using acnh.

**Comment by kutuo** [comment]
The previous version can also connect to the accelerator, maybe there is something wrong with my router related settings, I will study it again

**Comment by tuanzi11** [comment]
> The previous version can also connect to the accelerator, maybe there is something wrong with my router related settings, I will study it again
> 
>

**Comment by tuanzi11** [comment]
笔记本的电脑或者台式机电脑网线插在加速器上！我是加速盒子  笔记本网线插在加速器uu盒子接口

**Comment by tuanzi11** [comment]
> The previous version can also connect to the accelerator, maybe there is something wrong with my router related settings, I will study it again
> 
> 你看看你主机网络设置里面的ip多少
