### ISSUE TITLE
Bulldozer & Villager Replacement Crashing

### ISSUE THREAD

**Issue by demonElfe** [MyShiLingStar/ACNHPokerCore#23]
When I try to open Bulldozer and attempt to replace a villager ACNHPoker crashes and closes. Started happening with recent update download.

**Comment by demonElfe** [comment]
I tried rebooting and reinstalling. Windows is up to date but I continue to have the same issues. :\

**Comment by MyShiLingStar** [comment]
91eb3872fb380b82a00a653359f3836e7b51daf6
