### ISSUE TITLE
how to make nhbs files

### ISSUE THREAD

**Issue by kutuo** [MyShiLingStar/ACNHPokerCore#24]
I want to learn how to make nhbs files, I want to put more items on the ground, but nhi files can only put 40 at a time

**Comment by MyShiLingStar** [comment]
.nhbs is just a .nhi file with more than 40 items.



There are two ways to do it.
1. Use a hex editor like `HxD` to make one. You can make a few .nhi files and combine them in HxD.  
Every 8 bytes is one item.
![Hxd](https://user-images.githubusercontent.com/816502/179211831-a8e5c522-ea4b-49ae-9408-8b251f7f9c79.png)

2. Use an empty space in Map dropper and place your items. Then save the area to a .nhbs file.
Just remember the item order is `Top to down first, then left to right`.  
You should also remember the `height` of the spawn area if you want to spawn the item in the exact same way.
![Save](https://user-images.githubusercontent.com/816502/179213442-0e6c82fe-2d14-452e-964a-71cf88653bf3.png)

**Comment by kutuo** [comment]
thanks٩(๑>◡<๑)۶

**Comment by kutuo** [comment]
When I try to use HxD, I find that the item code is "0983", but it is "8309" in HxD, how can I convert the item code in batches？
<img width="377" alt="截屏2022-07-16 01 39 25" src="https://user-images.githubusercontent.com/93738387/179280812-0782000b-6755-459d-b774-04bf2813fb07.png">
<img width="248" alt="截屏2022-07-16 01 39 34" src="https://user-images.githubusercontent.com/93738387/179280981-f91a07b3-404c-40eb-96b7-32542ea72333.png">

**Comment by kutuo** [comment]
> 尝试使用HxD时，发现货品代码是“0983”，而在HxD中却是“8309”，如何批量转换货品代码？ <img alt="截屏2022-07-16 01 39 25" width="377" src="https://user-images.githubusercontent.com/93738387/179280812-0782000b-6755-459d-b774-04bf2813fb07.png"> <img alt="截屏2022-07-16 01 39 34" width="248" src="https://user-images.githubusercontent.com/93738387/179280981-f91a07b3-404c-40eb-96b7-32542ea72333.png">

I implemented the conversion in Excel, my knowledge is so lacking

**Comment by MyShiLingStar** [comment]
Yes, it is how `little-endian` works. You can learn more at [here](https://baike.baidu.com/item/Little-Endian).

![image](https://user-images.githubusercontent.com/816502/179341167-1c12cd4e-0bea-454f-b0cf-67516372ec66.png)
