### ISSUE TITLE
Bulldozer add acre

### ISSUE THREAD

**Issue by kutuo** [MyShiLingStar/ACNHPokerCore#25]
Can I add landing terrain on kappn‘s Island to Bulldozer?
These round reefs are so cute
<img width="1394" alt="截屏2022-07-18 06 17 16" src="https://user-images.githubusercontent.com/93738387/179426868-d5f366b3-201d-4d38-a165-def77eb7faee.png">

**Comment by ELY3M** [comment]
I always wear the same shirt :)    cool idea

**Comment by MyShiLingStar** [comment]
![image](https://user-images.githubusercontent.com/816502/179438179-125c7dd6-1724-44da-b2ca-58a6dc9fdff9.png)

To add something new, we need people to research and document them first.
I can't find anybody documenting the acre after 244. 

In theory, acre value can be 0x0000 to 0xFFFF (0 to 65535).
We currently have the data of the 0x0 to 0xF4 (0 to 244).
So there are still 0xFF0B (65,291) acres undocumented.

**Comment by MyShiLingStar** [comment]
![image](https://user-images.githubusercontent.com/816502/179492118-d971299d-f2f2-4f0e-ba7a-126792c23a0c.png)

**Comment by kutuo** [comment]
wow～～

**Comment by MyShiLingStar** [comment]
a7b74860765480f401bb02b3ddf49ed07ca5ddfc
