### ISSUE TITLE
Islands are often busy for no reason

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#29]
Why is it that sometimes after the bombing of the island, people get the password again, and others input the password and always show that they are busy

If map dropper is used before opening the island, it will also show that it is busy and cannot enter

I need to close the game completely to restart it

**Comment by z1006670445** [comment]
What is the reason? Can it be solved? How should I operate?

**Comment by MyShiLingStar** [comment]
Bombing? 💣💣?

The following are the things that need a restart to fix. There is no way around it. :  
1. Freeze/Set Time
2. Animation Speed
3. Disable Collision


Normal map dropper use should NOT require any restart.

**Comment by z1006670445** [comment]
> Bombing? 💣💣?
> 
> The following are the things that need a restart to fix. There is no way around it. :
> 
> 1. Freeze/Set Time
> 2. Animation Speed
> 3. Disable Collision
> 
> Normal map dropper use should NOT require any restart.

I found that before inviting , I used map dropper , and then opened the island to invite friends. Friends always remind me that the island is busy.

It is normal to open the island again after saving and exiting

**Comment by MyShiLingStar** [comment]
Map dropper should NOT cause any open gate problem.
What were you doing in Map dropper?


I tested the following:
1. Start Game
2. Use Map Dropper to replace spoiled turnips with the new one
3. Use Map Dropper to remove some weed
4. Close Map Dropper
5. Open the gate
6. People can fly in without a problem
