### ISSUE TITLE
It seems that this software does not support the latest Animal Crossing: New Horizons V2 05, because your other project is set to read-only. You can only be contacted here.

### ISSUE THREAD

**Issue by Ic-any** [MyShiLingStar/ACNHPokerCore#3]
Hello, I don't know why your other project seems to be set as read-only, but this matter is very important. I can only disturb you here. Sorry. Use ACHN port R18 At 8:00, the game version was 2.05. The functions of this software could not be used and displayed garbled codes, including the inability to modify the vegetable price, the inability to read and place items on the map, the inability to modify the time in the game, the inability to read residents, character names, item columns, etc.Please look at the picture below.I use machine translation, so the language is not very accurate.
![L Z0@8W2VOQ7 6)KO7W N6E](https://user-images.githubusercontent.com/92638461/154830020-67cadc60-1787-40d3-81a7-d02561ecd872.png)
![WO5{5)5J0`7$8JS%%8YW2@F](https://user-images.githubusercontent.com/92638461/154830026-2946c941-6b81-4390-8989-c581a2de6a1c.png)
![M0%M9E$7~EQY)F(C~Y87K~T](https://user-images.githubusercontent.com/92638461/154830028-0537ceb5-06e3-4dd8-9b51-3322b79fafed.png)
![2Y7OU0F4UUYQ)(`H{56F733](https://user-images.githubusercontent.com/92638461/154830032-44f40e87-6302-4993-9116-a8865c516f07.png)
![2G%G)1TTK}C)@3EG1L5$D)9](https://user-images.githubusercontent.com/92638461/154830035-e7f4e816-9c56-475b-8265-0d02b43c1d41.png)

**Comment by MyShiLingStar** [comment]
Yes, the old version does not work. 
Please update.
