### ISSUE TITLE
Activate/deactivate not working?

### ISSUE THREAD

**Issue by purzer0** [MyShiLingStar/ACNHPokerCore#32]
I tried toggling it on a gyroid, some gears, etc... it didn't do anything to turn them on or off.  Am I interpreting its function wrong?

**Comment by MyShiLingStar** [comment]
Due to how the game load stuff, the item you are toggling has to be off-screen.  
So run away or go inside a building first. Toggle it, then run back there to see it.

https://user-images.githubusercontent.com/816502/183538778-54d233d7-fe04-46d9-8725-be8ce38f978b.mp4

**Comment by purzer0** [comment]
Thanks, I had tried enabling while on-screen and then running back and forth, but next time I'll try enabling while off-screen :)
