### ISSUE TITLE
At present, there are only records of landing on the island. Can we also record the time of leaving the island

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#33]

**Comment by MyShiLingStar** [comment]
Possible. But it is difficult to keep track of. People could leave silently. 
Developing and testing it would require people to fly in and out of the island.
But I only have one single Switch myself so it is kind of difficult to work on it.

Low priority. But if for whatever reason I ever stream to Twitch again. I would try to add that in.

**Comment by z1006670445** [comment]
> 

Thank you very much. I think we can only consider the normal outlying islands. Those who leave silently will not be taken into account. If possible, I can help fly in and out of the island for your test

**Comment by ELY3M** [comment]
Good idea to add this in.   I also want to log the name and island of the person arriving and leaving.

**Comment by ELY3M** [comment]
I have plenty switches here so it wont be any issues for me to test.

**Comment by z1006670445** [comment]
> Good idea to add this in. I also want to log the name and island of the person arriving and leaving.

At present, there are records of the name and time of visiting the island

**Comment by ELY3M** [comment]
are we talking about the log in dodohelper?  

9/10/2022 8:33:43 PM : OverworldOrInAirport 2451
9/10/2022 8:33:45 PM : Unknown 2452
9/10/2022 8:33:48 PM : Unknown 2453
9/10/2022 8:33:51 PM : Unknown 2454
9/10/2022 8:33:53 PM : Unknown 2455
9/10/2022 8:33:56 PM : Unknown 2456
9/10/2022 8:33:59 PM : Unknown 2457
9/10/2022 8:34:01 PM : Unknown 2458
9/10/2022 8:34:04 PM : Unknown 2459
9/10/2022 8:34:07 PM : Unknown 2460
9/10/2022 8:34:09 PM : Unknown 2461
9/10/2022 8:34:12 PM : Unknown 2462
9/10/2022 8:34:15 PM : Unknown 2463
9/10/2022 8:34:17 PM : Unknown 2464
9/10/2022 8:34:20 PM : Unknown 2465
9/10/2022 8:34:23 PM : Unknown 2466
9/10/2022 8:34:25 PM : Unknown 2467
9/10/2022 8:34:28 PM : Unknown 2468
9/10/2022 8:34:31 PM : Unknown 2469
9/10/2022 8:34:33 PM : Unknown 2470
9/10/2022 8:34:36 PM : Unknown 2471
9/10/2022 8:34:39 PM : Unknown 2472
9/10/2022 8:34:41 PM : UserArriveLeavingOrTitleScreen 2473
9/10/2022 8:35:55 PM : Null 1
9/10/2022 8:35:58 PM : Null 2
9/10/2022 8:36:00 PM : Null 3
9/10/2022 8:36:03 PM : Null 4
9/10/2022 8:36:06 PM : Null 5
9/10/2022 8:36:08 PM : Null 6
9/10/2022 8:36:11 PM : Null 7
9/10/2022 8:36:14 PM : Null 8
9/10/2022 8:36:16 PM : Null 9
9/10/2022 8:36:19 PM : Null 10
9/10/2022 8:36:22 PM : Null 11
9/10/2022 8:36:24 PM : Null 12
9/10/2022 8:36:27 PM : OverworldOrInAirport 13
9/10/2022 8:36:30 PM : OverworldOrInAirport 14
9/10/2022 8:36:32 PM : OverworldOrInAirport 15
9/10/2022 8:36:35 PM : OverworldOrInAirport 16
9/10/2022 8:36:38 PM : OverworldOrInAirport 17
9/10/2022 8:36:40 PM : OverworldOrInAirport 18
9/10/2022 8:36:43 PM : OverworldOrInAirport 19
9/10/2022 8:36:46 PM : OverworldOrInAirport 20
9/10/2022 8:36:48 PM : OverworldOrInAirport 21
9/10/2022 8:36:51 PM : OverworldOrInAirport 22
9/10/2022 8:36:54 PM : OverworldOrInAirport 23
9/10/2022 8:36:56 PM : OverworldOrInAirport 24
9/10/2022 8:36:59 PM : OverworldOrInAirport 25
9/10/2022 8:37:02 PM : OverworldOrInAirport 26
9/10/2022 8:37:04 PM : OverworldOrInAirport 27
9/10/2022 8:37:07 PM : OverworldOrInAirport 28
9/10/2022 8:37:10 PM : OverworldOrInAirport 29
9/10/2022 8:37:13 PM : OverworldOrInAirport 30
9/10/2022 8:37:16 PM : OverworldOrInAirport 31
9/10/2022 8:37:18 PM : OverworldOrInAirport 32
9/10/2022 8:37:21 PM : OverworldOrInAirport 33
9/10/2022 8:37:24 PM : OverworldOrInAirport 34
9/10/2022 8:37:26 PM : OverworldOrInAirport 35
9/10/2022 8:37:29 PM : OverworldOrInAirport 36
9/10/2022 8:37:32 PM : OverworldOrInAirport 37
9/10/2022 8:37:35 PM : OverworldOrInAirport 38
9/10/2022 8:37:37 PM : OverworldOrInAirport 39
9/10/2022 8:37:40 PM : OverworldOrInAirport 40
9/10/2022 8:37:43 PM : OverworldOrInAirport 41
9/10/2022 8:37:45 PM : OverworldOrInAirport 42
9/10/2022 8:37:48 PM : OverworldOrInAirport 43
9/10/2022 8:37:51 PM : OverworldOrInAirport 44
9/10/2022 8:37:53 PM : OverworldOrInAirport 45
9/10/2022 8:37:56 PM : OverworldOrInAirport 46
9/10/2022 8:37:59 PM : OverworldOrInAirport 47
9/10/2022 8:38:01 PM : OverworldOrInAirport 48
9/10/2022 8:38:04 PM : OverworldOrInAirport 49
9/10/2022 8:38:07 PM : OverworldOrInAirport 50
9/10/2022 8:38:09 PM : OverworldOrInAirport 51
9/10/2022 8:38:12 PM : OverworldOrInAirport 52
9/10/2022 8:38:15 PM : OverworldOrInAirport 53
9/10/2022 8:38:18 PM : OverworldOrInAirport 54
9/10/2022 8:38:20 PM : OverworldOrInAirport 55
9/10/2022 8:38:23 PM : OverworldOrInAirport 56
9/10/2022 8:38:26 PM : OverworldOrInAirport 57
9/10/2022 8:38:28 PM : OverworldOrInAirport 58
9/10/2022 8:38:31 PM : OverworldOrInAirport 59
9/10/2022 8:38:34 PM : OverworldOrInAirport 60
9/10/2022 8:38:36 PM : OverworldOrInAirport 61
9/10/2022 8:38:39 PM : OverworldOrInAirport 62
9/10/2022 8:38:42 PM : OverworldOrInAirport 63
9/10/2022 8:38:44 PM : OverworldOrInAirport 64
9/10/2022 8:38:47 PM : OverworldOrInAirport 65
9/10/2022 8:38:50 PM : OverworldOrInAirport 66
9/10/2022 8:38:52 PM : OverworldOrInAirport 67
9/10/2022 8:38:55 PM : OverworldOrInAirport 68
9/10/2022 8:38:58 PM : OverworldOrInAirport 69
9/10/2022 8:39:00 PM : OverworldOrInAirport 70
9/10/2022 8:39:03 PM : OverworldOrInAirport 71
9/10/2022 8:39:06 PM : OverworldOrInAirport 72
9/10/2022 8:39:08 PM : OverworldOrInAirport 73
9/10/2022 8:39:11 PM : OverworldOrInAirport 74
9/10/2022 8:39:14 PM : OverworldOrInAirport 75
9/10/2022 8:39:16 PM : OverworldOrInAirport 76
9/10/2022 8:39:19 PM : OverworldOrInAirport 77
9/10/2022 8:39:22 PM : OverworldOrInAirport 78
9/10/2022 8:39:24 PM : OverworldOrInAirport 79
9/10/2022 8:39:27 PM : OverworldOrInAirport 80
9/10/2022 8:39:30 PM : OverworldOrInAirport 81
9/10/2022 8:39:32 PM : OverworldOrInAirport 82
9/10/2022 8:39:35 PM : OverworldOrInAirport 83
9/10/2022 8:39:38 PM : OverworldOrInAirport 84
9/10/2022 8:39:40 PM : OverworldOrInAirport 85
9/10/2022 8:39:43 PM : OverworldOrInAirport 86
9/10/2022 8:39:46 PM : OverworldOrInAirport 87
9/10/2022 8:39:49 PM : OverworldOrInAirport 88
9/10/2022 8:39:51 PM : OverworldOrInAirport 89
9/10/2022 8:39:54 PM : OverworldOrInAirport 90
9/10/2022 8:39:57 PM : OverworldOrInAirport 91
9/10/2022 8:39:59 PM : OverworldOrInAirport 92
9/10/2022 8:40:02 PM : OverworldOrInAirport 93
9/10/2022 8:40:05 PM : OverworldOrInAirport 94
9/10/2022 8:40:07 PM : Null 95
9/10/2022 8:40:10 PM : Null 96
9/10/2022 8:40:13 PM : Null 97
9/10/2022 8:40:16 PM : Null 98
9/10/2022 8:40:18 PM : Null 99
9/10/2022 8:40:21 PM : Null 100
9/10/2022 8:40:24 PM : Null 101
9/10/2022 8:40:26 PM : Null 102
9/10/2022 8:40:29 PM : Null 103
9/10/2022 8:40:32 PM : Null 104
9/10/2022 8:40:34 PM : Null 105
9/10/2022 8:40:37 PM : Unknown 106
9/10/2022 8:40:40 PM : UserArriveLeavingOrTitleScreen 107
9/10/2022 8:40:43 PM : UserArriveLeavingOrTitleScreen 1
9/10/2022 8:40:46 PM : UserArriveLeavingOrTitleScreen 1
9/10/2022 8:40:49 PM : Unknown 1
9/10/2022 8:40:52 PM : Unknown 2
9/10/2022 8:40:54 PM : Unknown 3
9/10/2022 8:40:57 PM : Unknown 4
9/10/2022 8:41:00 PM : Unknown 5
9/10/2022 8:41:03 PM : Unknown 6
9/10/2022 8:41:05 PM : OverworldOrInAirport 7
9/10/2022 8:41:08 PM : OverworldOrInAirport 8
9/10/2022 8:41:11 PM : OverworldOrInAirport 9
9/10/2022 8:41:14 PM : OverworldOrInAirport 10
9/10/2022 8:41:16 PM : OverworldOrInAirport 11
9/10/2022 8:41:19 PM : OverworldOrInAirport 12
9/10/2022 8:41:22 PM : OverworldOrInAirport 13

**Comment by ELY3M** [comment]
9/12/2022 1:50:48 AM : Unknown 5213
9/12/2022 1:50:50 AM : UserArriveLeavingOrTitleScreen 5214
9/12/2022 1:50:51 AM : newVisitor: Kelly
9/12/2022 1:52:04 AM : OverworldOrInAirport 1
9/12/2022 1:52:07 AM : OverworldOrInAirport 2
9/12/2022 1:52:10 AM : OverworldOrInAirport 3

**Comment by ELY3M** [comment]
We need to find offset for getting island name of the visitor 

public static UInt32 VisitorNameAddress = 0xB750ED78; //0xB710ED78;

**Comment by ELY3M** [comment]
I decided best solution for me is auto take captures as visitor arrive. 

                        if (!newVisitor.Equals(string.Empty))
                        {
                            CreateLog(newVisitor);
                            WriteLog("newVisitor: "+newVisitor, true);
                            //capture visitor's arrival lol
                            Thread.Sleep(1000);
                            Controller.ClickCAPTURE();
                            Thread.Sleep(1000);
                            Controller.ClickCAPTURE();
                            Thread.Sleep(1000);
                            Controller.ClickCAPTURE();
                            Thread.Sleep(1000);
                            Controller.ClickCAPTURE();
                            WriteLog("Took Captures", true);
                            Thread.Sleep(70000);
                            Utilities.sendBlankName(s);
                            state = Teleport.GetOverworldState();
                        }
                    }

**Comment by z1006670445** [comment]
> I decided best solution for me is auto take captures as visitor arrive.
> 
> ```
>                     if (!newVisitor.Equals(string.Empty))
>                     {
>                         CreateLog(newVisitor);
>                         WriteLog("newVisitor: "+newVisitor, true);
>                         //capture visitor's arrival lol
>                         Thread.Sleep(1000);
>                         Controller.ClickCAPTURE();
>                         Thread.Sleep(1000);
>                         Controller.ClickCAPTURE();
>                         Thread.Sleep(1000);
>                         Controller.ClickCAPTURE();
>                         Thread.Sleep(1000);
>                         Controller.ClickCAPTURE();
>                         WriteLog("Took Captures", true);
>                         Thread.Sleep(70000);
>                         Utilities.sendBlankName(s);
>                         state = Teleport.GetOverworldState();
>                     }
>                 }
> ```

I find offset for getting island name of the visitor


public static UInt32 VisitorNameAddress = 0xB750ED78; //0xB710ED78;
public static UInt32 VisitorIslandNameAddress = VisitorNameAddress - 0x1C;

**Comment by z1006670445** [comment]
> Possible. But it is difficult to keep track of. People could leave silently. Developing and testing it would require people to fly in and out of the island. But I only have one single Switch myself so it is kind of difficult to work on it.
> 
> Low priority. But if for whatever reason I ever stream to Twitch again. I would try to add that in.

Hello, is the name and time of the outlying island difficult? This function is important to me. If we need help with the test, we can make an appointment. I will find two or three friends to help me with the test. Will it be faster?

**Comment by z1006670445** [comment]
I don't think we need to consider leaving the island silently. We just need to consider leaving normally

**Comment by MyShiLingStar** [comment]
![image](https://user-images.githubusercontent.com/816502/198586258-64af831d-8a1c-4ecb-928f-00ae9035f587.png)
6eeb96d47a291adcc4068e13dfffd4c427f8fd47
