### ISSUE TITLE
irregular move out and Forced move out

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#44]
What's the difference between these two?

Is my understanding wrong?

irregular move out：All Villagers move, and all of them will be moved to empty space the next day
 Forced move out：All Villagers move. When the time comes to two days, only one of them will move and become vacant, and then the second small animal will be prompted to move

**Comment by MyShiLingStar** [comment]
Before version 1.5.0 :
Forced move out : The villager will move out on the next day. 
Irregular move out : The villager will be stuck in the move out state forever.

But Nintendo has changed the move out sequence in the recent versions.
And I haven't spent the time to test out how they work. All I know is that they will no longer stay forever. 
You can use whichever one you like. 

And if you want them to stay move out forever, try the freeze villager option.
