### ISSUE TITLE
Map Regenerator Issues

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#45]
I click Cast Regen and occasionally there is no progress bar. Why? How can I avoid this situation

![QQ截图20221015211035](https://user-images.githubusercontent.com/35718635/195988269-04564d50-e7d7-4f38-b09e-ca34c3a6485f.png)

**Comment by z1006670445** [comment]
If the progress bar does not appear, everything is normal except that the log does not record

**Comment by MyShiLingStar** [comment]
The regenerator has been tested to run over 24 hours without any problem.

I have no idea how you crash the progress bar.
Can you please provide the steps/video to reproduce the problem?

**Comment by z1006670445** [comment]
This is video .Restart the poker, and the probability will be normal


https://user-images.githubusercontent.com/35718635/195996201-635b9854-c040-4fe6-9fdc-7e19c107fa73.mp4

**Comment by z1006670445** [comment]
Disconnect and then connect again. There is still no progress bar. It will be normal only when the poker is restarted

**Comment by z1006670445** [comment]
Because github video size is limited, it is not very high-definition


Uploading 格式工厂 屏幕录像20221016_000353~1.mp4…

**Comment by z1006670445** [comment]
Because github video size is limited, it is not very high-definition


https://user-images.githubusercontent.com/35718635/195996613-3718e5c8-9109-48cb-9412-67ef320e7c0a.mp4

**Comment by z1006670445** [comment]
> If the progress bar does not appear, everything is normal except that the log does not record

video is upload，thank you

**Comment by z1006670445** [comment]
This is a reproduction video. Specific steps:

Open Regenerator

Then click Enable Dodo Helper

Then click Cast Regen to select the file

Then Dodo helper clicks Abort in the process of opening the island

Start Cast Regen again, and the progress bar will not be displayed

https://user-images.githubusercontent.com/35718635/195997635-964151fd-2d0e-414e-8ddc-64fc97ea91ba.mp4

**Comment by MyShiLingStar** [comment]
Should be fixed on 977b711ca09ff5f7dd72195958e4263b1b621d12
Please download the latest build.
