### ISSUE TITLE
I can't add new items to my backpack

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#46]
After I updated 977b711 today, I can't add new items to my backpack

https://user-images.githubusercontent.com/35718635/196029893-178929ac-e69b-44d1-a2ed-03de961f548e.mp4

**Comment by MyShiLingStar** [comment]
Nothing has changed related to the inventory item spawn.
Please ensure you did not activate the "Freeze Inventory" in the "Freezer" menu.

**Comment by z1006670445** [comment]
Thankes.After I click UnFreeze Inventory in Freezer, it is normal, but I'm sure I haven't clicked Freeze Inventory in Freezer before, and I don't know where I misoperated
