### ISSUE TITLE
Poker Issue

### ISSUE THREAD

**Issue by Colton07** [MyShiLingStar/ACNHPokerCore#5]
Hi my poker is not showing my my island name & items $ the names of things are in a different language is there a fix to this? Everything in the "Others" tab seems to be fine accept for the reactions.

**Comment by MyShiLingStar** [comment]
Make sure your game has been updated to version 2.0.5.
And you are using "ACNHPokerCore for v2.0.5
![2022-02-28_11-50-27](https://user-images.githubusercontent.com/816502/155916080-a8d97271-cdee-4855-b660-5c751ec41b26.png)
"
