### ISSUE TITLE
About interface text localization

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#51]
I want to change some labels and button titles displayed in the program into Chinese. Is there a better way? Or can I only change one interface by one through C #? Is it feasible to put the language pack in the specified location?

**Comment by z1006670445** [comment]
Or we can use the resx provided by C #

![image](https://user-images.githubusercontent.com/35718635/197957503-4be6c436-a1d5-42f7-9bc5-2c07fcffcaf4.png)

**Comment by MyShiLingStar** [comment]
The easiest way to do this is indeed using the resx file.

1. Make the form "Localizable".
2. Change to the language you want to localize.
3. Edit the text.
4. Check the code and see if it changes the text.
5. Edit the code to handle the localization change.

4 and 5 might be complex in some cases. You can try doing 1 - 3 first, which should cover most of the text.

**Comment by tuanzi11** [comment]
怎么做到本地化中文界面🥹
