### ISSUE TITLE
The props cannot be deleted. After the software is closed, they can be thrown to the ground indefinitely

### ISSUE THREAD

**Issue by Ic-any** [MyShiLingStar/ACNHPokerCore#52]
After the software is closed, items can be repeatedly dropped on the ground, instead of the normal game. Items dropped on the ground will disappear.Deleting in the software will still refresh repeatedly. I have reopened the game several times but still can't solve it

https://user-images.githubusercontent.com/92638461/198832000-26bc1e17-30ff-4eff-9919-4622ed248ead.mp4

**Comment by MyShiLingStar** [comment]
Freezer -> Unfreeze Inventory
