### ISSUE TITLE
CANNOT load my island and inventory correctly!

### ISSUE THREAD

**Issue by kyphans** [MyShiLingStar/ACNHPokerCore#58]
This is not my data
![image](https://user-images.githubusercontent.com/51189352/210420533-9d6607ff-ea92-4fe8-8b94-6cf5579b9c5a.png)
![image](https://user-images.githubusercontent.com/51189352/210421036-f453cebe-6559-491a-b036-66bec00ca152.png)
![Uploading image.png…]()

I tried creating a new island and still got

**Comment by moddedx** [comment]
Are you running any cheat or mods?

**Comment by kyphans** [comment]
> Are you running any cheat or mods?

Im not sure. But I restarted my Switch and reconnected to ACNH Poker and it still doesn't work.  it shows incorrect data for my island

**Comment by kyphans** [comment]
> > Are you running any cheat or mods?
> 
> Im not sure. But I restarted my Switch and reconnected to ACNH Poker and it still doesn't work. it shows incorrect data for my island

I don't run any cheats

**Comment by tuanzi11** [comment]
删除这个 插件0000000000534c56就正常了Poker

**Comment by kyphans** [comment]
Working! nice 
Thanks bro!

> 删除这个 插件0000000000534c56就正常了Poker
