### ISSUE TITLE
sys-botbase says not installed when it is

### ISSUE THREAD

**Issue by kmj9702** [MyShiLingStar/ACNHPokerCore#61]
Hi !! I recently updated my switch to 16.0, i have atmosphere (the prerelease), and hekate installed, as well as JKSV, acnh poker was working perfect before i had to update my switch and the CFW, but now it says i don’t have sys-bot base installed when i do, i have the current version as well, i’ve even tried older versions and it still doesn’t work, it’s in atmosphere/contents/ and then the numbered folder, my joycon doesn’t light up blue anymore either and i’m not sure how to fix this? it’s not my internet, i even tried connecting to my mobile hotspot and it still wouldn't work, it's not any firewall issues either as it was working just fine a few hours ago, any help would be appreciated (:

**Comment by moddedx** [comment]
sysbot-base is on the switch and the blue light will come on when placed correctly on the sd card and does not depend on a network connection. If you copied sysbot-base over the the sd card after updating it might be in the wrong location/folder.

**Comment by kmj9702** [comment]
> sd

it belongs in the atmosphere/contents folder right? that's where i've put it, i can send picture of where it is when i get home. but i've tried using sys-botbase 22, 211 and 21 i believe and can't get any of them to work, currently sys-botbase 22 is on my sd card.

**Comment by MyShiLingStar** [comment]
The flashing LED is a clear indicator that sys-botbase is running correctly. 
**If you do not see the LED flashing**, it is possible that sys-botbase is not running correctly. 

In that case, please check your sys-botbase installation once again. 
You might also want to try a `Fix Archive Bit` in Hekate menu as well.
Boot up in Hekate, Goto `Tools` -> `Archive bit・AutoRCM・Touch Tuning` -> `Fix Archive Bit`.
Boot into CFW and see if the LED is flashing.

**Comment by kmj9702** [comment]
> The flashing LED is a clear indicator that sys-botbase is running correctly. 
> 
> **If you do not see the LED flashing**, it is possible that sys-botbase is not running. 
> 
> 
> 
> In that case, please check your sys-botbase installation once again. 
> 
> You might also want to try a `Fix Archive Bit` in Hekate menu as well.
> 
> Boot up in Hekate, Goto `Tools`  -> `Fix Archive Bit`.
> 
> ![image](https://user-images.githubusercontent.com/816502/224466385-c0cbff06-76cb-4385-81e3-b2fcb626901d.png)
> 
> Boot into CFW and see if the LED is flashing.




I did the fix archive, still no flashing LED


i might just do a clean install of my CFW and see if that works. I installed sys-botbase 22 into atmosphere/contents/43000000 and in that folder is flags and exefs.nsp

**Comment by kmj9702** [comment]
I fixed it ! just did kind of a clean install. wiped everything off my SD card except my nintendo folder, JKSV folder, and config folder. reinstalled atmosphere & hekate, then it wouldn't let me launch so i put my bootloader and payloads back on my SD card and reinstalled sys-bot into atmosphere/content and it worked !!
