### ISSUE TITLE
Potential Emulator Support

### ISSUE THREAD

**Issue by Corban-Lee** [MyShiLingStar/ACNHPokerCore#62]
This works great on my modded switch, however I've started to emulate and I'm really missing this editor. Are there any plans to support emulators such as Ryujinx and is it even possible?

I see #17 but was still wondering if this means emulator support will always be dead?

**Comment by moddedx** [comment]
That is correct as sysbotbase will not work on an emulator.

**Comment by MyShiLingStar** [comment]
Emulator support has been added in the Pastryon/OnlyFats build.
