### ISSUE TITLE
sysdvr causing issues

### ISSUE THREAD

**Issue by BelleButCode** [MyShiLingStar/ACNHPokerCore#64]
Under device manager my swsitch is named SysDVr instead of Nintendo SwitchI believe is causing errors with recognition pls help how fix ashiduhawiouhfdajhshdihhaewfdjaosjd.

**Comment by ELY3M** [comment]
This is wrong place.   you need to head to sysdvr github repo

**Comment by MyShiLingStar** [comment]
I am closing this issue as stale. Because Beri said that it is a dumb issue.
