### ISSUE TITLE
Not connecting to switch.

### ISSUE THREAD

**Issue by nbdeity** [MyShiLingStar/ACNHPokerCore#72]
IDK if it's because i'm in the tutorial or because i used [this](https://gamebanana.com/mods/470713), but no matter if i load with mods on or off it will not connect to my console. even though i have the proper versions of everything and the right ip address.

My game wast started in japanese, dunno if that makes a difference
here's what it shows:

![ACNHPokerCore_arsNOohGw6](https://github.com/MyShiLingStar/ACNHPokerCore/assets/65470941/01b2e509-1ae0-40c4-9c4a-ad37ee91e1da)

**Comment by MyShiLingStar** [comment]
Please check
https://github.com/MyShiLingStar/ACNHPokerCore/issues/71
