### ISSUE TITLE
Doesn’t connect to my IP

### ISSUE THREAD

**Issue by rhimcyy** [MyShiLingStar/ACNHPokerCore#73]
I see a lot of people having the same issue under the YouTube video titled “ACNH poker tutorial”. I installed sys bot base correctly as my switch tells me so, I put in the right IP adress and it always says “ACNH poker has crashed” crashes and comes up with the error fix stuff (did everything it told me to). I even tried installing every version of sys bot base and seeing if each one would work. Unfortunately it didn’t. Is this something wrong with the program or it’s too outdated? Just wanted to know as this mod looked great it just never works.

**Comment by MyShiLingStar** [comment]
Please provide a screenshot of the error message that you received.
If there is a "more detail" page, please also provide that info too.

**Comment by rhimcyy** [comment]
Hello thank you for your response here’s the error message I’m getting, I’ve looked further into it and I’ve installed everything correctly and have the latest version of animal crossing and my system says sys bot base is running correctly as it says “AMS” by my software in the photos below. I’ve also put the correct IP in on the system (also shown below) tried restarting my software and done everything the error message has told me and still not working. I don’t have any other mods installed that would mess this up either.
![IMG_0837](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/3482f8f2-b8b4-46d6-acfd-5e26d2ca78f6)
![IMG_0835](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/861abd95-3bf5-4093-a063-517f4d6830da)
![IMG_0834](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/9bfa9d6d-84d9-47d6-80ad-2be64c87c8a1)
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/4ee83c83-d005-427a-831a-0150ddd4a8f6)

![IMG_0838](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/a6522d02-04f2-40a2-a036-4de5756a9768)
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/514436db-957c-4a0b-a8f9-d351e60067a7)

**Comment by moddedx** [comment]
If sysbot-base was installed correctly the home button will glow blue on startup. Post screen shot of the contents folder within atmosphere folder.

**Comment by MyShiLingStar** [comment]
This is how the joy-con LED looks like when you boot up the Switch: 
![LED](https://user-images.githubusercontent.com/816502/172078166-d21caa5a-c50e-47ed-acae-18e970f88a94.gif)
But since you are using a third-party joy-con. It might not have the LED for the home button.


Please check the following location: `SD: \ atmosphere \ contents`
It should contain a folder for sys-botbase: `430000000000000B`
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/eba91971-d625-4c97-a350-c35b03af945d)


If you are sure that everything above is correct,
then it is possible that your network might have blocked the connection of sys-botbase.
You can try setting up a Wifi hotspot using your mobile phone.
Then connect both your PC and your Switch to that Wifi hotspot then try again.

**Comment by rhimcyy** [comment]
Heya thank you for helping yet again unfortunately neither worked :( used my iPhone hotspot with my switch and computer and the same error message came up. And yes haha they aren’t the usual joycons so I don’t think the home button would light up as these are pretty cheap ones and for some reason they flash constantly. Here’s the screenshots of my SD card and contents folder :)
![IMG_0844](https://github.com/MyShiLingStar/ACNHPokerCore/assets/157094288/c01353dd-d777-4345-aba0-e86848407398)

**Comment by MyShiLingStar** [comment]
There is your problem. You did not install sys-botbase correctly.
Here is what it looks like inside `430000000000000B`
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/3a6479c2-783c-4525-af4b-237c1f28146e)
The `flag` folder and the `exefs.nsp` file.
Here is what it looks like inside the `flag` folder
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/e4594987-5c3a-4233-8336-834b2fa7d953)
The `boot2.flag` file.

There is no `sys-botbase-2.31` folder at all.

**Comment by rhimcyy** [comment]
Thank you so much I couldn’t find any tutorials on YouTube that were clear of how to install sys bot base clearly. Just me being stupid again thank you for your time and helping me with my issue! :)
