### ISSUE TITLE
Crashes when opening Bulldozer

### ISSUE THREAD

**Issue by wisteriacrossing** [MyShiLingStar/ACNHPokerCore#77]
Pretty self-explanatory, PokerCore crashes when loading the bulldozer function on newest release (R23) Please lmk if you need more info! Thank youuuu :)

**Comment by MyShiLingStar** [comment]
Please hold the left side `shift` button on your keyboard while selecting the `bulldozer` options.

![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/019bf7c4-55f2-4b13-8c11-06e7f5557c36)

![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/05044722-f033-40c4-9892-4eede85b324a)
You should receive a `File saved!` prompt and a folder named `Your` next to the .exe file.

Please upload all 4 files here for further investigation.
You can drag and drop the files into the comment box to upload them.

**Comment by CR33PERYT** [comment]
Hi, I have the same problem, so here are my files, if it helps, thank you in advance
[Files.zip](https://github.com/MyShiLingStar/ACNHPokerCore/files/14625498/Files.zip)

**Comment by MyShiLingStar** [comment]
Thx, I think I found one of the problem.

But why you have a player house 8 but no player house 1?
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/ecfe4d02-64ec-45d4-8b0e-0231eb334fad)

**Comment by CR33PERYT** [comment]
It's a save that I modified to modify some things, I tried to change my tent to a house but it didn't work, I can put it back to 0 if that's the problem.

**Comment by wisteriacrossing** [comment]
Thank you so much for your help! Here are my files:
[Your.zip](https://github.com/MyShiLingStar/ACNHPokerCore/files/14628464/Your.zip)

**Comment by MyShiLingStar** [comment]
Should have been fixed on the latest build.
Please download again.
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/66dd3200-b8e5-4a3a-b7d1-fb49b3409baa)

**Comment by wisteriacrossing** [comment]
Awesome, yes it works now thank youuuu!
