### ISSUE TITLE
About MapDropper freezing

### ISSUE THREAD

**Issue by adolncom** [MyShiLingStar/ACNHPokerCore#8]
When I use MapDropper on ACNHPokerCore, I keep getting a Please Wait message.
Residents, pockets, bells, etc. are fine.
When I spawn or delete in the MAP, the Please Wait appears and no progress is made at all.
I have sys-botbase-211, latest version.
ACNHPokerCore also has the latest version.

**Comment by MyShiLingStar** [comment]
The "Please Wait" means autosave protection is kicking in.
It means it is unsafe to spawn an item so poker stopped and wait for a better time.
Normally, it should resume the operation after waiting for a bit.


If it does not resume, it could mean something is wrong with the autosave.

Did the "Est. Next Save" value show something unusual?
The normal value should be between 0 to 179, and it should keep counting down and repeating.
![image](https://user-images.githubusercontent.com/816502/162198024-328c1182-4a39-4fb4-99fa-4be5cad86814.png)

Did you get the message about turning autosave protection off?
![image](https://user-images.githubusercontent.com/816502/162198929-e892c276-a376-409b-bee1-c154c21585f3.png)

Are you running the game in another language instead of English?

**Comment by adolncom** [comment]
MyShiLingStar
Est.NextSave" is 3205366... The number is decreasing from 3205366....

Did you get the message about turning autosave protection off?
No.
Are you running the game in another language instead of English?
I use English. My wife uses Japanese.

**Comment by MyShiLingStar** [comment]
Hmm... not sure why you have an extremely large value for the estimated save time...
If possible, please post a screenshot of the whole map dropper window like the one below.
![image](https://user-images.githubusercontent.com/816502/162215779-fe5394b8-484b-435f-a51c-8c0f7de96291.png)


I have also just pushed a new commit and ignored the very large value for now.
Please download the new version again at [Here](https://berichan.github.io/GetNHSE/?org=MyShiLingStar&proj=ACNHPokerCore&projurl=https://github.com/MyShiLingStar/ACNHPokerCore) and see if it allow you to use the map dropper.

And do both of you have the Happy Home Paradise DLC installed?

**Comment by adolncom** [comment]
![image](https://user-images.githubusercontent.com/67450852/162218961-ba41baab-69bb-4672-b080-2fd53624ab3b.png)

Happy Home Paradise DLC 
Yes

I put in a new Coer.
I also created a new folder, but it is the same.
3205358 numbers are coming down a bit.

**Comment by MyShiLingStar** [comment]
Does the new build work?
The problem has nothing to do with the folder. The estimated save time is calculated from the value on your switch.
And for some reason, yours is reporting some very big numbers.

If possible, try pulling down the Poker main window And type "**457B05AC**" and click the "**Peek**" button
![image](https://user-images.githubusercontent.com/816502/162232673-40db96c6-47c4-4f47-9013-8740d6ad73ea.png)

And post the result here:
![image](https://user-images.githubusercontent.com/816502/162232773-dd533eb6-de21-41da-95e1-839f8c5ee2bc.png)

**Comment by adolncom** [comment]
![image](https://user-images.githubusercontent.com/67450852/162234161-52062b15-7236-4db3-95f0-9a16b59f6021.png)

Thank you for using your valuable time.
We appreciate it.

**Comment by MyShiLingStar** [comment]
Hmmm...Your memory result does not look right at all.
I will need to look into it later. I can not reproduce it at the moment.

![image](https://user-images.githubusercontent.com/816502/162239881-95bbeff6-2bb4-44ea-8ed7-57fd8004c1a5.png)
It does not seem to be a DLC problem too. I just installed it and it is giving me the correct value in the same memory address.

![image](https://user-images.githubusercontent.com/816502/162244746-20130ffd-1c76-4dda-93ff-560b9ab5e4bc.png)
Does the critter spawner read the correct data for you?
Please let me know if you find other stuff that does not work.

**Comment by MyShiLingStar** [comment]
I tried for quite a while but I still can't reproduce the problem.

But I have added the options to disable the autosave protection.
Just **double-click** the "Est. Next Save" and the number will turn red.
It will ignore the autosave protection and let you spawn your item.
![image](https://user-images.githubusercontent.com/816502/164161957-a091f30e-daeb-4dfe-9f63-b63d3a2ceb4e.png)

**Comment by adolncom** [comment]
Thank you for taking the time to do this for me.
I am now able to spawn safely.
I really appreciate it.
You are a wonderful creator.
