### ISSUE TITLE
I have already connected to ACNHPokerCore through sys-botbase, but the retrieved data is incorrect. I'm unable to obtain user data.

### ISSUE THREAD

**Issue by luoergou666** [MyShiLingStar/ACNHPokerCore#80]
<img width="900" alt="{946B27C0-D234-40ad-979E-512EB4F9C00D}" src="https://github.com/MyShiLingStar/ACNHPokerCore/assets/44280137/a87753f9-f463-412f-b310-7b279aba95f0">

**Comment by MyShiLingStar** [comment]
Please see https://github.com/MyShiLingStar/ACNHPokerCore/issues/69

**Comment by luoergou666** [comment]
> 请参见#69

Thank you for your reply. I wish you a wonderful day. Thank you!
