### ISSUE TITLE
Fossils Request

### ISSUE THREAD

**Issue by typative** [MyShiLingStar/ACNHPokerCore#87]
Hi again! 

I was wondering if it'd be possible for you to add a Fossils tab/section in Poker? Especially for non assessed and then another for assessed. I know the assessed fossils are in there and we can pull them by typing in their name.. but that's kind of a pain lol

So anyway, just thought I'd ask this. I still love love love Poker 🙂

**Comment by MyShiLingStar** [comment]
To create unassessed fossils:
1. Left mouse click the item `fossil` (ID : 0A13)
2. Right mouse click the actual fossil. (Skull, torse, tail ... etc)
3. Spawn the fossil item.

You can also just load these nhi files : [Fossil nhi](https://github.com/user-attachments/files/17516578/fossil.zip)

https://github.com/user-attachments/assets/a74cab89-b0a9-4888-8f3f-4b5cecf1ad3c

**Comment by typative** [comment]
Omg awesome! Sorry, I never knew about this!! Ty!! 🙂
