### ISSUE TITLE
Using Map Dropper to "Place" Wall items?

### ISSUE THREAD

**Issue by typative** [MyShiLingStar/ACNHPokerCore#88]
Hi there. I'm sorry, this might not be an actual issue. Might be something I just don't know yet. But I've tried like everything. 
I'm doing a treasure island, and I'm trying to "place" Dreamy Wall Racks outside. I've tried every variable shown when you mouse over the flag field/option in Map Dropper. If it's not buried, then it's placed but invisible. Yet it's there somehow bc I can't walk thru the space where it's at. But if you look up, even walk away and look up, you don't see anything. What am I missing, or is this an issue in Poker's map dropper? I'm using the latest/current version, R23.

**Comment by MyShiLingStar** [comment]
Wall-mounted items require the wall displays to be placed properly.

Left-mouse click one of the wall displays.
Right-mouse click the item you want to mount.
![image](https://github.com/user-attachments/assets/d40a1b8c-e14e-45da-ba92-371645c4aa10)

**Comment by typative** [comment]
Oh okay, Ty so much!! 🙂




~ Sent from my iOS device

**Comment by typative** [comment]
Hmm.. I tried all that but it's not working.. 🙁






~ Sent from my iOS device

**Comment by typative** [comment]
Nvm I got it now! Sorry for bothering you! Ty soooo much again!! 🙂




~ Sent from my iOS device
