### ISSUE TITLE
Crash caused by Road Roller, now no Snowballs

### ISSUE THREAD

**Issue by typative** [MyShiLingStar/ACNHPokerCore#90]
I started yet another new island, and was using Poker to form some of the island how I want using the Road Roller portion. While that was loading/saving, it caused the game to crash. That brown screen and I had to close out of AC and open again. Ever since then, I literally have not had any snowballs appear. Even though they've been a daily achievement. I've tried everything I can think of. I used NHSE to change to Southern hemisphere for a day then went back to Northern. Still the same. So I them went back a couple of weeks before snow completely covered the grass, and went day by day. Still no snowballs though. Any suggestions? And can you add in snowballs as an item in Poker for us to pull/spawn?

**Comment by MyShiLingStar** [comment]
Nothing in poker editing is related to the snowball spawning.
The game crashing will only cause you to lose your latest edit before your last save. Again, this is not related to the snowball.

All I can think of is that you might not have enough empty space for the snowball to spawn.
You can try clearing out an open area with empty snow ground and ensure it is not covered by any custom design.
Also, try to avoid any cliff or water near it.

**Comment by typative** [comment]
Hmm.. I've tried all of that.. there's plenty of space for snowballs.. it's
just not happening, ever since that crash. This happened a while back too..
back then I ended up having to trash that island completely and start over.
I'm really trying to avoid having to start over this time.

Oh and it crashed two times actually. Once while using Bulldozer, which I
used the first tab in there.. got rid of a river from the bottom, moved the
dock for where Kapp'n will be from the right to the left, along with the
back mini beach section where Red will dock his boat from right to left..
crashed while saving those I think too.. that, or adjusting where the homes
for the first two villagers (I don't remember exactly).

But speaking of that first tab in Bulldozer.. I only recently started
playing around with those.. all this time, I never knew we could do that!!
LoL, so cool!! 🙂

Anyway.. I'm gonna continue on with this island until after I've unlocked
the permits etc, to see if I still don't get snowballs.. if that's still
the case, I guess I'll be starting over.




~ Sent from my iOS device

**Comment by MyShiLingStar** [comment]
Just a small tip if you want to avoid the crash in the future.
You can keep your inventory open like the image below. It will stop the game's auto-save.
The edit might take longer to save, but it should prevent most of the brown screen crashes.

I will see if I can find more information about snowball spawning. But I don't think people have done much about it.

![image](https://github.com/user-attachments/assets/00a7912b-9203-487f-a864-87877aac54fc)

**Comment by typative** [comment]
Okay. And regarding the snowballs, apparently it was related to me still
being in the tutorial stage.. once I got 3 stars and sat thru that kk
concert etc, snowballs were back. That's dumb tho. I had daily achievements
to build snow folk. Oh well.

Sorry to have bothered you for this though.

I seriously love your Poker app!! 😁




~ Sent from my iOS device
