### ISSUE TITLE
The latest version  webpage won't open.

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#91]
https://myshilingstar.github.io/GetAzure/  

It shows "Unable to access."

![image](https://github.com/user-attachments/assets/fa4a3f47-7a35-4af8-8f47-aaf749aa2e6f)

**Comment by moddedx** [comment]
Loaded just fine on my end.
Latest pokercore
https://dev.azure.com/MyShiLingStar/b95f815c-31ee-49cb-a3d5-d3911a68b6f4/_apis/build/builds/95/artifacts?artifactName=ACNHPokerCore&api-version=6.0&%24format=zip
.net7 files
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=7.0.0&arch=x64&rid=win10-x64&gui=true

**Comment by z1006670445** [comment]
> Loaded just fine on my end. Latest pokercore https://dev.azure.com/MyShiLingStar/b95f815c-31ee-49cb-a3d5-d3911a68b6f4/_apis/build/builds/95/artifacts?artifactName=ACNHPokerCore&api-version=6.0&%24format=zip .net7 files https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=7.0.0&arch=x64&rid=win10-x64&gui=true

thanks！
